name: LeetCode Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Compile and Run Java Program
      run: |
        java -cp target/classes:target/dependency/* LeetCodeAutomation
        
    # - name: Compile and Run Java Program
    #   run: |
    #     javac LeetCodeAutomation.java
    #     java LeetCodeAutomation
